### ISSUE TITLE
TIP: Better not to use non-standard ports

### ISSUE THREAD

**Issue by sullof** [tronprotocol/tron-grid#1]
In many corporate networks, it's possible to access HTTP only on port 80 and HTTPS only on port 443.
This causes that to access https://api.trongrid.io:8090 someone has to ask the net manager to open the ports. It is a very common problem and I propose that we solve it using subdomains like:
```
https://fullnode.apigrid.io
https://soliditynode.apigrid.io
https://eventserver.apigrid.io
```
This approach is also self-explanatory. And, anyway, we can keep the current ports open for retro-compatibility.
For brevity, we can also have aliases like `https://fn.apigrid.io` for `https://fullnode.apigrid.io`.

**Comment by sullof** [comment]
Alternatively, we could remap the APIs, with URLs like `https://api.apigrid.io/fullnode/...`.

**Comment by kookiekrak** [comment]
I've remapped 

`api.trongrid.io/wallet` to fullnode

`api.trongrid.io/walletsolidity` and `api.trongrid.io/walletextension` to solidity node

all are accessible over https on 443
