### ISSUE TITLE
trongrid api gateway timeouts

### ISSUE THREAD

**Issue by zero24x** [tronprotocol/tron-grid#10]
hi,

recently im getting timeouts from the api, please check it. my indexing site (https://dappstatcentral.ml) for tron dapps is blocked.

thx for helping!

i send maybe 1 request per second for 5min every 30minutes so im flooding your api, right?

 https://api.trongrid.io/v1/accounts/TVBAfSQsk9jvPWzLTNRVZiE8ix656HKaUZ/transactions/?min_timestamp=1556517705001&sort=block_timestamp&size=200&onlyConfirmed=true
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1>< (truncated...)

**Comment by sullof** [comment]
@zero24x That API is experimental. We completed the public testing and are preparing for the launch. In the meantime we are dismissing the machines used for the MVP, that means that there can be downtime all the time. I suggest you to wait for the official launch before using that API in production.

**Comment by zero24x** [comment]
hello @sullof thanks for your fast reply, and i appreciate the effort of offering developers/community the trongrid api so they can build things with it!

**Comment by zero24x** [comment]
hi, when can i expect the above url to work now please, how long until the api service is stable and fast to be usable?

@sullof 

i am getting an 504 gateway error now still!

**Comment by sullof** [comment]
We are distributing the database and improving the reliability of the service before launching it officially. That API, anyway, should work, even if it is not totally reliable. But only in America, because in other region it will be very slow, since the db is, for now, only in the US.

**Comment by sullof** [comment]
We will announce it, when ready. It should be this week, I hope.

**Comment by vahidfzm** [comment]
Invest needs a valid address as Referrer and I fixed it by defining a default value.
