### ISSUE TITLE
Pagination compatibility

### ISSUE THREAD

**Issue by hiendv** [tronprotocol/tron-grid#9]
Hi, I'm trying to get a list of events with pagination support. Because tron-grid does not support `page` and local event server does not support `_fingerprint`.
I'm asking for a pagination method to use in both local and tron-grid server.

**Comment by hiendv** [comment]
ping @sullof

**Comment by sullof** [comment]
To have next page, just add the fingerprint to next request. In TronWeb, you can add the property to the options object passed to getEventResult.

**Comment by hiendv** [comment]
@sullof Well, the thing is, local tron event server (tron quickstart) does not support `_fingerprint`

**Comment by hiendv** [comment]
@sullof Please re-open the issue

**Comment by sullof** [comment]
That is not possible. The Eventron code uses Tron Quickstart for the test unit, and in the tests there are extensive tests about pagination.

**Comment by sullof** [comment]
Try to use the new format 
```
http://localhost:9090/v1/contracts/[contract_address]/events
```

**Comment by sullof** [comment]
Even better, use the new TrongridJS lib
https://github.com/TRON-US/trongrid-js
Use it only for events because the account/asset API are in testing and require an accessCode

**Comment by hiendv** [comment]
@sullof So basically, I have to write different codes to paginate the events depending on the event server?
```
if (trongrid)
    use fingerprint
else
    use page
```

**Comment by hiendv** [comment]
The trongrid-js library is not public though.

**Comment by manish8561** [comment]
nile test network fingerprint not working properly
